VirusTotal/vt-py

examples/url_feed.py
vt/feed.py

Adds an example for "URL" feed
Addresses #16
edit: force pushed since i had my email in the commit

add url feed

---

vt/feed.py

not tested because I don't have an authorized API key for the feeds

Add support for sandbox behaviour feed

---

vt/client.py
vt/iterator.py

As mentioned in #30 the Iterator class currently does not properly parse collections when limit=0.  Took a stab at fixing this with this PR.

Fix for interator class when limit=0

---

tests/test_iterator.py
vt/iterator.py

Fix None value returned between batches

---

tests/test_client.py
vt/client.py

Add timeout parameter to VT client

---

docs/source/conf.py
examples/create_reference.py
examples/file_behaviour_feed.py
examples/file_feed.py
examples/file_feed_async.py
examples/file_provenance.py
examples/hunting_notifications_to_network_infrastructure.py
examples/import_yara_ruleset.py
examples/intelligence_search_to_network_infrastructure.py
examples/retrohunt_to_network_infrastructure.py
examples/search.py
examples/suspicious_network_observables.py
examples/url_feed.py
setup.py
vt/__init__.py
vt/client.py
vt/error.py
vt/feed.py
vt/iterator.py
vt/object.py

This pull request was created with the command [`pyupgrade --py36-plus **/*.py`](https://github.com/asottile/pyupgrade#readme)
Python f-strings simplify the code and [should speed up execution](https://www.scivision.dev/python-f-string-speed).

Upgrade to modern Python syntax

---

tests/test_client.py
vt/client.py

implements https://github.com/VirusTotal/vt-py/issues/69#issuecomment-897718494

feat(scan_file): Check file argument is a file object

---

examples/upload_files.py

Fixes `upload_files.py` example, it was broken by #70.
closes #33 
closes #40

fix(examples): Fix and improve upload_files.py example

---

vt/client.py

Fix issue#111 by forcing the content-type in the request

---

vt/client.py

feat: Parametrize verify SSL on Client object

---

examples/download_files.py
vt/client.py

closes #113 and https://github.com/VirusTotal/vt-py/issues/111#issuecomment-1255057664

fix: Fix broken example in Python 3.10

---

vt/client.py
vt/version.py

This is a more robust alternative to https://github.com/VirusTotal/vt-py/pull/124.

Fix issue #125

---

vt/utils.py

Reverts VirusTotal/vt-py#127
closes #130 
closes #132

Revert "fix async error"

---

examples/download_files.py

fix(download files example): Don't create empty files if a file can't be downloaded

---

examples/g.py

Console 1-click tool to download files from VT. It could be extremely handy to malware analysts in their day-to-day job.

Adding g.py

---

examples/search_behavior_mbc.py

Create an example to print out MBC data that is present in file behavior signatures. 
Example 
```
$ pipenv run ./examples/search_behavior_mbc.py  --apikey $VT_API_KEY
2023-06-08 11:29:16 INFO     Starting MBC Fetch example
2023-06-08 11:29:16 INFO     * VirusTotal Intelligence search: sandbox_name:CAPA and fs:2023-06-07T00:00:00+
2023-06-08 11:29:16 INFO     * Number of files to fetch: 10
sha256: 052a56a677d51899758524a72fa6daf900e82766597997b5503e6cf53d9116a3  mbc:Anti-Static Analysis::Software Packing::UPX [F0001.008]
sha256: d06b1fd6fc8bc8b03ce9a7bc9a901ded8acc09e7c613287cad76aefb4d77a7ca  mbc:Operating System::Registry::Create Registry Key [C0036.004]
sha256: d06b1fd6fc8bc8b03ce9a7bc9a901ded8acc09e7c613287cad76aefb4d77a7ca  mbc:Operating System::Registry::Open Registry Key …
```

add example to search file behavior and print MBC data

---

examples/suspicious_network_observables.py

Issue: https://github.com/VirusTotal/vt-py/issues/149

Initial commit: use ipaddress standard library to validate IP address

---

examples/enqueue_url_scan.py
examples/import_yara_ruleset.py
examples/search_behavior_mbc.py

```
************* Module enqueue_url_scan
examples/enqueue_url_scan.py:62:10: E1123: Unexpected keyword argument 'loop' in constructor call (unexpected-keyword-arg)
************* Module import_yara_ruleset
examples/import_yara_ruleset.py:99:10: E1123: Unexpected keyword argument 'loop' in constructor call (unexpected-keyword-arg)
************* Module search_behavior_mbc
examples/search_behavior_mbc.py:74:0: W1405: Quote delimiter ' is inconsistent with the rest of the file (inconsistent-quotes)
```

fix(ci): Fix pylint issues

---

vt/client.py

feat: Add custom connectors to the client

---

docs/source/howtoinstall.rst

fix(docs): Install instructions

---

vt/version.py

fixes https://github.com/VirusTotal/vt-py/issues/195

fix: bump version

---

.github/workflows/testing.yaml
examples/upload_files.py

fix: Encoding error in upload files example
