VirusTotal/vt-py

- examples/file_feed.py
- examples/file_feed_async.py
- tests/test_client.py
- vt/feed.py
Missing packages are not common, but can happen. This doesn't means that we are loosing feed items, it just means that no package was created for one minute. Also make some improvements to the file feed examples.
> Make the feed iterator able to tolerate a missing package.

- vt/client.py
Most WSGI apps doesn't have an event loop set (although they are technically running on an event loop, this is, the main process where the app is running), so we cannot convert an asynchronous task in a sync one because we don't know where to execute the tasks that are supposed to be executed in our async task.
As a quick fix and while Python frameworks for developing WSGI apps allow to use Async IO natively (seems that Django is working on it https://docs.djangoproject.com/en/3.0/topics/async/ and Tornado already have a workaround https://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.AsyncIOMainLoop), the easiest way to avoid users struggling with the integration of vt-py and WSGI apps is to generate an event loop if the app vt-py is running on has not defined one.
> Generate event loop for WSGI applications

- setup.py
vt-py requires python 3.6+ 
asyncio from pypi is only required for python3.3 - https://pypi.org/project/asyncio/
> remove asyncio from pypi requirements

- tests/test_client.py
- tests/test_iterator.py
- vt/iterator.py
closes #24 
```python
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vt
>>> client = vt.Client('xxxx')
>>> it = client.iterator('/domains/google.com/downloaded_files', limit=3)
>>> next(it)
<vt.object.Object object at 0x1056fc5d0>
>>> next(it)
<vt.object.Object object at 0x1056fced0>
>>> next(it)
<vt.object.Object object at 0x1056f4d10>
>>> next(it)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mgmacias/Documents/GitHub/vt-py/vt/iterator.py", line 147, in __next__
raise StopIteration()
StopIteration
```
> Add support for next in iterator object

- vt/object.py
Before:
```python
>>> import vt
>>> client = vt.Client('xxx')
>>> it = client.iterator('/domains/google.com/downloaded_files', limit=3)
>>> list(it)
[<vt.object.Object object at 0x10ae53fd0>, <vt.object.Object object at 0x10ae53f90>, <vt.object.Object object at 0x10aa0f250>]
```
After:
```python
>>> import vt
>>> client = vt.Client('xxx')
>>> it = client.iterator('/domains/google.com/downloaded_files', limit=3)
>>> list(it)
[<vt.object.Object file 45bf8866af1dfdbfc4177d3807df43221e87bd3037d6681b4bd3d8b402376f9e>, <vt.object.Object file ec7ee9eb45069d5716658a384b9c6738543ae20c60004dfbf7c6abcffa38a134>, <vt.object.Object file 10a01be40c332fffbbad2df799c98d6a45af24cd78a10c264f37c51b7fc50869>]
```
Having both `__str__` and `__repr__` improves usability and readability :)
> Add __str__ and __repr__ to the Object class

- examples/enqueue_url_scan.py
- examples/file_behaviour_feed.py
- examples/file_provenance.py
- examples/import_yara_ruleset.py
- examples/intelligence_search_to_network_infrastructure.py
- examples/search_similar_files.py
- examples/suspicious_network_observables.py
- examples/upload_files.py
- examples/url_feed.py
- vt/feed.py
This PR adds more example scripts in the `examples/` directory:
* `enqueue_url_scan.py`: receives either a single URL or a file containing a URL per file. Enqueues all URL to be scanned.
```shellsession
$ python enqueue_url_scan.py --apikey xxxxx --url https://google.com
URL https://google.com enqueued for scanning.
```
* `file_behaviour_feed.py`: an example to fetch the file behaviour feed. Prints files that either drop an executable or launch a powershell.
```shellsession
$ python file_behaviour_feed.py --apikey xxxx
b4a2994ee366e996f8c072766143b8cb20910c19b09ec2164667ef35ab2539a9
398347895787081ddbe518a3e5ec68bb9ce0e3695a2580f6a374c011fd362b01
0fb80643ad6ddbc25fd31bbe7f22a451b38a389d01b9876705c2accc46352f66
92384fd0cd7374975b32a1019c7c76af17881ad0a743d905d6e9e712ce93c3e7 …
```
> Additional examples

- vt/client.py
Adding proxy support for `aiohttp.ClientSession` per the docs: https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession
`trust_env` (bool) - Get proxies information from HTTP_PROXY / HTTPS_PROXY environment variables if the parameter is True (False by default). Get proxy credentials from ~/.netrc file if present.
Tested through the public internet and behind through our proxy and the network calls are successful.
> Adding proxy support via aiohttp.ClientSession trust_env

- .travis.yml
- docs/_modules/vt/client.html
- docs/_modules/vt/feed.html
- docs/_sources/overview.rst.txt
- docs/_sources/quickstart.rst.txt
- docs/api/client.html
- docs/overview.html
- docs/quickstart.html
- docs/source/overview.rst
- docs/source/quickstart.rst
- examples/file_behaviour_feed.py
- vt/client.py
- vt/feed.py
This PR was created via [codespell --ignore-words-list="nd" --skip="\*.css,\*.js,*.svg" -w](https://github.com/codespell-project/codespell)
> Fix typos discovered by codespell

- .github/workflows/publishing.yaml
This reverts commit 50408817983236c901715f20338c3abbafb86640.
Already tested package publishing at https://github.com/VirusTotal/vt-py/actions/runs/1185385961.
> Revert "Temporary manual trigger for publishing action (#73)"

- tests/test_client.py
- vt/client.py
closes #82 
closes #42 
Usage example:
```python
>>> import vt
>>> c = vt.Client('myapikey')
>>> import io
>>> b = io.BytesIO()
>>> c.download_zip_files(['cc59cf71470cb076591aa35e59c39375cfcdb68f92405979f289aa6806269369'], b, 'pass')
>>> import zipfile
>>> with zipfile.ZipFile(b) as f:
...     print(f.namelist())
... 
['cc59cf71470cb076591aa35e59c39375cfcdb68f92405979f289aa6806269369']
>>> with zipfile.ZipFile(b) as f:
...     with f.open(f.namelist()[0], pwd=b'pass') as z:
...             print(hashlib.sha256(z.read()).hexdigest())
... 
cc59cf71470cb076591aa35e59c39375cfcdb68f92405979f289aa6806269369
```
> feat(client): Download password protected zip files

- vt/client.py
- vt/version.py
This prevents leaking aiohttp.ClientSession objects that complain about unclosed event loops when the program exits.
> Call `close` when `vt.Client` is destroyed.

- vt/utils.py
when use `async with ` syntax, there will raise RuntimeError
and after this change, there no error raise
> fix async error

- .gitignore
- examples/upload_files.py
- vt/client.py
I encountered `AttributeError: 'coroutine' object has no attribute 'stats'` when I was using upload_files.py. This is how I fixed the issue.
**Original Code:**
```python
async def process_analysis_results(apikey, analysis, file_path):
async with vt.Client(apikey) as client:
completed_analysis = await client.wait_for_analysis_completion(analysis)
print(f'{file_path}: {completed_analysis.stats}')
```
**Modified Code:**
```python
async def process_analysis_results(apikey, analysis, file_path):
async with vt.Client(apikey) as client:
completed_analysis = await client.wait_for_analysis_completion(analysis)
analysis_result = await completed_analysis
print(f'{file_path}: {analysis_result.stats}')
```
**Explanation:**
In the original code, the `stats` attribute is directly accessed from the …
> Fix 'coroutine' object has no attribute 'stats' error in analysis results for upload_files.py

- tests/test_feed.py
- tests/test_iterator.py
This is a bit opinionated PR that removes `pylint: disable=unused-argument` and use `@pytest.mark.usefixtures`.
Pytest provides `usefixtures` marker to use a fixture. It enables to use a fixture without having it as an argument.  `pylint: disable=unused-argument` is not necessary if you use it.
(See https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#use-fixtures-in-classes-and-modules-with-usefixtures for details) 
I think it's cleaner than inline-disabling the lint rule.
> test: use usefixtures

- tests/test_client.py
- vt/object.py
fixes #172
This PR changes the class `WhistleBlowerDict` to inherit from a `UserDict` instead of inheriting directly from `dict`. This is a best practice and resolves the issue when pickling the object.
> fix(object): Load a pickled vt object

- tests/test_client.py
- vt/client.py
- vt/object.py
closes #176 
The `json.dumps` function only accepts native types by default (i.e. `list`, `dict`, `str`, `int`, etc etc) but it is not prepared to parse user custom types such as `UserDict`. To parse custom types, it is required to extend the default `JsonEncoder` class available at the `json` module. This PR does this, and integrates it into the aiohttp's client session.
This PR also updates the tests to support this use case since the problem was not the dictionary representing the object itself but the `context_attributes` dictionary inside the object which is an instance of the `WhistleBlowerDict` class.
> fix(object): Object of type WhistleBlowerDict is not JSON serializable

- setup.py
aiohttp has dropped Python 3.7 y recent versions, so to not break clients using this library (as the Splunk integration) I'm fixing the last aiohttp version compatible with 3.7.
> Fix: Fix aiohttp version to be compatible with Python 3.7

- setup.py
The recently merged MR https://github.com/VirusTotal/vt-py/pull/184 broke Python 3.12 compatibility.
This patch fixes that while keeping aiohttp pinned to 3.8.6 for Python 3.7
Merging this would be highly appreciated as distros start rolling out Python 3.12
> Pin aiohtp to 3.8.6 for python 3.7; use a newer version for python > 3.7

- .github/workflows/testing.yaml
- setup.py
- tests/test_client.py
- tests/wsgi_app.py
- vt/client.py
closes #183 
The VT Client expected to be called inside an asyncio coroutine and when it was not (for example, when running non-async wsgi apps) it raised a runtime error exception because there was no event loop. This PR fixes that.
> fix(client): Fix Runtime error when running non async apps

- examples/private_scan.py
- tests/test_client.py
- vt/client.py
Fixes #182
- Added `scan_file_private()` and `scan_file_private_async()` methods
- Implemented Code Insight support for private scans
- Private scanning via `private=1` parameter
- Code Insight via `code_insight` flag
- Support for both sync/async operations
- Progress tracking with rich console output
- Proper file handle management
- Enhanced error handling
- All tests passing
- Manually tested with example script
> Add private scan support with code insight

- .github/workflows/testing.yaml
- examples/hunting_notifications_to_network_infrastructure.py
- examples/intelligence_search_to_network_infrastructure.py
- examples/livehunt_network_watch.py
- examples/private_scan.py
- examples/retrohunt_to_network_infrastructure.py
- pylintrc
- setup.py
- tests/test_client.py
- tests/test_feed.py
- tests/test_iterator.py
- vt/client.py
- vt/feed.py
- vt/iterator.py
- vt/object.py
- vt/utils.py
> chore: Linting

- .github/workflows/publishing.yaml
Migrate to trusted publishers using the steps described at https://docs.pypi.org/trusted-publishers/using-a-publisher/
> chore: Migrate to trusted publishers

- tests/test_client.py
- vt/client.py
- vt/object.py
Implement #210. 
This is a bit opinionated PR but, from a user's point of view, I think it makes this library more usable.
> refactor: convert UserDict (WhistleBlowerDict) into plain dict

- tests/test_client.py
- vt/client.py
When file/url scan is triggered, the current implementation always checks the current job stats via ```/analyses``` path in ```wait_for_anaysis_completion``` function
But when a private file/url scan is triggered, the same URI path is being used which will yield ```NotFoundError``` because the private file/url uses ```/private/analyses``` path instead.
> Fix private file scan
